### ISSUE TITLE
go version?

### ISSUE THREAD

**Issue by srenatus** [chainguard-images/ko#6]
Sorry for asking such basic questions, but I've been wondering which go (and ko) version I'd get when using this image... it seems like the container definition doesn't say much about it (it's just "go" and "ko" there); running the image tells me:

```
$ docker run -it --entrypoint /bin/sh distroless.dev/ko 
/ $ go version
go version go1.19 linux/amd64
/ $ ko version
(devel)
```
So... What needs to be done to get go updated to 1.19.1? And ko to its latest version, too, maybe? 🤔 

Thanks!

**Comment by amouat** [comment]
At this moment, we're tracking the Alpine packages for Go and ko. The image updates automatically when those packages are updated. I see Go is at 1.19.1 in the latest image.

In the future, I expect to have a wolfi based build, which should allow us to update even faster.

I'll close this issue for the moment, but let me know if anything isn't clear.

**Comment by srenatus** [comment]
> I'll close this issue for the moment, but let me know if anything isn't clear.

Yup, 1.19.1 is in there. The `ko version` output leaves a few things to be desired, though -- what a version is "devel"?

> In the future, I expect to have a wolfi based build, which should allow us to update even faster.

Cool. Looking forward to that.
